# PyTorch Basic 

<hr>

## What is PyTorch

PyTorch is an open source framework for machine learning (ML) and Deap Learning (DL) implementation.

There are various frameworks such as Detectron2, mmdetection that build upon PyTorch to make DL processs more easier. We will see these frameworks later on.

## PyTorch Tensor

Tensor is basic unit for handling numerical data for DL processing. By applying arithmetic operations, especially dot product, DL can update weights and bias of the neural network to train the model. We will see specific steps on building neural network, predicting result, computing loss function, and updating weights and bias. But in this note, I will only focus on how to use tensor through PyTorch.

# PyTorch Tensor

<hr>

## Import PyTorch and Check Version

Let's Start with importing PyTorch and checking PyTorch Version

In [60]:
import torch
torch.__version__

'1.9.1+cu111'

## 1. Scalar

A Scalar is a single number like 0, 1, 2 ... However, it is in tensor form with a sero dimension tensor.

In [61]:
scalar = torch.tensor(1)
print("Scalar: ", scalar)
print("Scalar Dimension: ", scalar.ndim)
print("Scalar item: ", scalar.item()) #Retrieving the number from the tensor. Only works for tensor with one element

Scalar:  tensor(1)
Scalar Dimension:  0
Scalar item:  1


## 2. Vector

From high school, you should rememeber what is a vector. A vector is a single dimension tensor but contains several numbers. If you are familar with programming, it is more of a like list, but in tensor form. 

In [62]:
vector = torch.tensor([7,7])
print("Vector: ", vector)
print("Vector Dimension: ", vector.ndim)
print("Vector Shape: ", vector.shape) 
#shape returns number of element in 1 dimension tensor

Vector:  tensor([7, 7])
Vector Dimension:  1
Vector Shape:  torch.Size([2])


## 3. Matrix

Let's move further down to matrix. You can think of matrix as concanation of multiple list in column-wise or stacking multiple lists on top of each other. Matrix is two dimension tensor. 

In [63]:
matrix = torch.tensor([[7,8, 9],
                      [10,11,12]])
print("Matrix: ")
print(matrix)
print("Matrix Dimension: ", matrix.ndim)
print("Matrix Shape: ", matrix.shape) #First item represent number of rows, second item represent number of columns of the matrix

Matrix: 
tensor([[ 7,  8,  9],
        [10, 11, 12]])
Matrix Dimension:  2
Matrix Shape:  torch.Size([2, 3])


## 4. Tensor

Now, some of you might never heard about tensor. In my case, I never heard about tensor including my high school and college, even though I am CS major :(

Easy way to think of tensor is stacking the multiple matrix like a book. You can think of each page is a maxtrix with numbers. Then your are stacking matrix on top of each other which makes a book! Then, we can call book itself is a tensor. Tensor is three dimension tensor "<b>tensor</b>" :)

In [64]:
tensor = torch.tensor([[[1, 2, 3],  #First page of the book
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10,11,12], #Second page of the book
                        [13,14,15],
                        [16,17,18]]])
print("Tensor:")
print(tensor)
print("Tensor Dimension: " ,tensor.ndim)
print("Tensor Shape: ", tensor.shape)
#Fist item is number of page, second Item is number of rows, Third item is number of column
#Note that number of column, number of row must be same for all pages 


Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Tensor Dimension:  3
Tensor Shape:  torch.Size([2, 3, 3])


# Useful PyTorch Libary

<hr>

PyTorch also has various useful libaries for generating random tensor, changing shape from one dimension to other dimension. These are useful when you start implementing DL for weight calcuations and predicting results :)



## Random Tensor

Random Tensor library assigned arbitary values into the tensor size you choose. You will see these random tensor vary often when you are initializing the weights of the baisc neural network. Specific detail about weight initialization will be discussed on in basic neural network part.

### 1. Vector (+ Scalar)

In [65]:
random1 = torch.rand(3) 
#Generating 3 column "Vector" tensor
#When you put size "1" it generate size 1 "Vector" tensor. However, it can be treated as scalar.
print("Random1: ")
print(random1)
print("Random1 Dimension: ", random1.ndim)
print("Random1 Shape: ", random1.shape)
print("Random1 data type: ", random1.dtype)
#Basic dtype of rand library is Float32. There are various dtype you can find in PyTorch website.

Random1: 
tensor([0.0301, 0.4753, 0.6493])
Random1 Dimension:  1
Random1 Shape:  torch.Size([3])
Random1 data type:  torch.float32


### 2. Matrix

In [66]:
random2 = torch.rand(size=(3,2)) 
#generating 3 rows, 2 column "Matrix" tensor
print("Random2: ")
print(random2)
print("Random2 Dimension: ", random2.ndim)
print("Random2 Shape: ", random2.shape)
print("Random2 data type: ", random2.dtype)

Random2: 
tensor([[0.9407, 0.0456],
        [0.7313, 0.6886],
        [0.3951, 0.7675]])
Random2 Dimension:  2
Random2 Shape:  torch.Size([3, 2])
Random2 data type:  torch.float32


### 3. Tensor

In [67]:
random3 = torch.rand(size=(2,3,2)) 
#Generating 2 dimension, 3 rows, 2 column "Tensor" tensor
print("Random3: ")
print(random3)
print("Random3 Dimension: ", random3.ndim)
print("Random3 Shape: ", random3.shape)
print("Random3 data type: ", random3.dtype)

Random3: 
tensor([[[0.2408, 0.2619],
         [0.3795, 0.5457],
         [0.5724, 0.5800]],

        [[0.7716, 0.1713],
         [0.3952, 0.8441],
         [0.3990, 0.1870]]])
Random3 Dimension:  3
Random3 Shape:  torch.Size([2, 3, 2])
Random3 data type:  torch.float32


# Zeros and Ones

Sometimes when are "masking" weight (which means manipulating weight for special purpose), we need zero or one values of tensor. This work exactly the same way as random tensor library. 

### 1. Vector (+ Scalar)

In [68]:
zeros1 = torch.zeros(3)
print("Zeros1: ")
print(zeros1)
print("Zeros1 Dimension: ", zeros1.ndim)
print("Zeros1 Shape: ", zeros1.shape)
print("Zeros1 data type: ", zeros1.dtype)
print("----------------------------------")
ones1 = torch.ones(3)
print("Ones1: ")
print(ones1)
print("Ones1 Dimension: ", ones1.ndim)
print("Ones1 Shape: ", ones1.shape)
print("Ones1 data type: ", ones1.dtype)

Zeros1: 
tensor([0., 0., 0.])
Zeros1 Dimension:  1
Zeros1 Shape:  torch.Size([3])
Zeros1 data type:  torch.float32
----------------------------------
Ones1: 
tensor([1., 1., 1.])
Ones1 Dimension:  1
Ones1 Shape:  torch.Size([3])
Ones1 data type:  torch.float32


### 2. Matrix

In [69]:
zeros2 = torch.zeros(3,2)
print("Zeros2: ")
print(zeros2)
print("Zeros2 Dimension: ", zeros2.ndim)
print("Zeros2 Shape: ", zeros2.shape)
print("Zeros2 data type: ", zeros2.dtype)
print("----------------------------------")
ones2 = torch.ones(3,2)
print("Ones2: ")
print(ones2)
print("Ones2 Dimension: ", ones2.ndim)
print("Ones2 Shape: ", ones2.shape)
print("Ones2 data type: ", ones2.dtype)

Zeros2: 
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
Zeros2 Dimension:  2
Zeros2 Shape:  torch.Size([3, 2])
Zeros2 data type:  torch.float32
----------------------------------
Ones2: 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
Ones2 Dimension:  2
Ones2 Shape:  torch.Size([3, 2])
Ones2 data type:  torch.float32


### 3. Tensor

In [70]:
zeros3 = torch.zeros(2, 3,2)
print("Zeros3: ")
print(zeros3)
print("Zeros3 Dimension: ", zeros3.ndim)
print("Zeros3 Shape: ", zeros3.shape)
print("Zeros3 data type: ", zeros3.dtype)
print("----------------------------------")
ones3 = torch.ones(2,3,2)
print("Ones3: ")
print(ones3)
print("Ones3 Dimension: ", ones3.ndim)
print("Ones3 Shape: ", ones3.shape)
print("Ones3 data type: ", ones3.dtype)

Zeros3: 
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
Zeros3 Dimension:  3
Zeros3 Shape:  torch.Size([2, 3, 2])
Zeros3 data type:  torch.float32
----------------------------------
Ones3: 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
Ones3 Dimension:  3
Ones3 Shape:  torch.Size([2, 3, 2])
Ones3 data type:  torch.float32


## Ranging Tensors

Rangind tensor library enables user to set start and end number with specific step to generate the tensor. 