# PyTorch Basic 

<hr>

## 1. What is PyTorch

PyTorch is an open source framework for machine learning (ML) and Deap Learning (DL) implementation.

There are various frameworks such as Detectron2, mmdetection that build upon PyTorch to make DL processs more easier. We will see these frameworks later on.

## 2. PyTorch Tensor

Tensor is basic unit for handling numerical data for DL processing. By applying arithmetic operations, especially dot product, DL can update weights and bias of the neural network to train the model. We will see specific steps on building neural network, predicting result, computing loss function, and updating weights and bias. But in this note, I will only focus on how to use tensor through PyTorch.

# PyTorch Tensor

<hr>

## Import PyTorch and Check Version

Let's Start with importing PyTorch and checking PyTorch Version

In [1]:
import torch
torch.__version__

'1.9.1+cu111'

## 1. Scalar

A Scalar is a single number like 0, 1, 2 ... However, it is in tensor form with a sero dimension tensor.

In [2]:
scalar = torch.tensor(1)
print("Scalar: ", scalar)
print("Scalar Dimension: ", scalar.ndim)
print("Scalar item: ", scalar.item()) #Retrieving the number from the tensor. Only works for tensor with one element

Scalar:  tensor(1)
Scalar Dimension:  0
Scalar item:  1


## 2. Vector

From high school, you should rememeber what is a vector. A vector is a single dimension tensor but contains several numbers. If you are familar with programming, it is more of a like list, but in tensor form. 

In [3]:
vector = torch.tensor([7,7])
print("Vector: ", vector)
print("Vector Dimension: ", vector.ndim)
print("Vector Shape: ", vector.shape) 
#shape returns number of element in 1 dimension tensor

Vector:  tensor([7, 7])
Vector Dimension:  1
Vector Shape:  torch.Size([2])


## 3. Matrix

Let's move further down to matrix. You can think of matrix as concanation of multiple list in column-wise or stacking multiple lists on top of each other. Matrix is two dimension tensor. 

In [4]:
matrix = torch.tensor([[7,8, 9],
                      [10,11,12]])
print("Matrix: ")
print(matrix)
print("Matrix Dimension: ", matrix.ndim)
print("Matrix Shape: ", matrix.shape) #First item represent number of rows, second item represent number of columns of the matrix

Matrix: 
tensor([[ 7,  8,  9],
        [10, 11, 12]])
Matrix Dimension:  2
Matrix Shape:  torch.Size([2, 3])


## 4. Tensor

Now, some of you might never heard about tensor. In my case, I never heard about tensor including my high school and college, even though I am CS major :(

Easy way to think of tensor is stacking the multiple matrix like a book. You can think of each page is a maxtrix with numbers. Then your are stacking matrix on top of each other which makes a book! Then, we can call book itself is a tensor. Tensor is three dimension tensor "<b>tensor</b>" :)

In [5]:
tensor = torch.tensor([[[1, 2, 3],  #First page of the book
                        [4, 5, 6],
                        [7, 8, 9]],
                       [[10,11,12], #Second page of the book
                        [13,14,15],
                        [16,17,18]]])
print("Tensor:")
print(tensor)
print("Tensor Dimension: " ,tensor.ndim)
print("Tensor Shape: ", tensor.shape)
#Fist item is number of page, second Item is number of rows, Third item is number of column
#Note that number of column, number of row must be same for all pages 


Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])
Tensor Dimension:  3
Tensor Shape:  torch.Size([2, 3, 3])


# Useful PyTorch Libary

<hr>

PyTorch also has various useful libaries for generating random tensor, changing shape from one dimension to other dimension. These are useful when you start implementing DL for weight calcuations and predicting results :)



> ## Random Tensor

Random Tensor library assigned arbitary values into the tensor size you choose. You will see these random tensor vary often when you are initializing the weights of the baisc neural network. Specific detail about weight initialization will be discussed on in basic neural network part.

### 1. Vector (+ Scalar)

In [6]:
random1 = torch.rand(3) 
#Generating 3 column "Vector" tensor
#When you put size "1" it generate size 1 "Vector" tensor. However, it can be treated as scalar.
print("Random1: ")
print(random1)
print("Random1 Dimension: ", random1.ndim)
print("Random1 Shape: ", random1.shape)
print("Random1 data type: ", random1.dtype)
#Basic dtype of rand library is Float32. There are various dtype you can find in PyTorch website.

Random1: 
tensor([0.0696, 0.7740, 0.1112])
Random1 Dimension:  1
Random1 Shape:  torch.Size([3])
Random1 data type:  torch.float32


### 2. Matrix

In [7]:
random2 = torch.rand(size=(3,2)) 
#generating 3 rows, 2 column "Matrix" tensor
print("Random2: ")
print(random2)
print("Random2 Dimension: ", random2.ndim)
print("Random2 Shape: ", random2.shape)
print("Random2 data type: ", random2.dtype)

Random2: 
tensor([[0.7072, 0.1874],
        [0.4934, 0.3700],
        [0.8373, 0.3203]])
Random2 Dimension:  2
Random2 Shape:  torch.Size([3, 2])
Random2 data type:  torch.float32


### 3. Tensor

In [8]:
random3 = torch.rand(size=(2,3,2)) 
#Generating 2 dimension, 3 rows, 2 column "Tensor" tensor
print("Random3: ")
print(random3)
print("Random3 Dimension: ", random3.ndim)
print("Random3 Shape: ", random3.shape)
print("Random3 data type: ", random3.dtype)

Random3: 
tensor([[[0.9024, 0.1928],
         [0.8302, 0.5785],
         [0.2093, 0.3398]],

        [[0.7614, 0.3758],
         [0.0158, 0.9138],
         [0.8219, 0.1703]]])
Random3 Dimension:  3
Random3 Shape:  torch.Size([2, 3, 2])
Random3 data type:  torch.float32


> ## Zeros and Ones

Sometimes when are "masking" weight (which means manipulating weight for special purpose), we need zero or one values of tensor. This work exactly the same way as random tensor library. 

### 1. Vector (+ Scalar)

In [9]:
zeros1 = torch.zeros(3)
print("Zeros1: ")
print(zeros1)
print("Zeros1 Dimension: ", zeros1.ndim)
print("Zeros1 Shape: ", zeros1.shape)
print("Zeros1 data type: ", zeros1.dtype)
print("----------------------------------")
ones1 = torch.ones(3) 
print("Ones1: ")
print(ones1)
print("Ones1 Dimension: ", ones1.ndim)
print("Ones1 Shape: ", ones1.shape)
print("Ones1 data type: ", ones1.dtype)

Zeros1: 
tensor([0., 0., 0.])
Zeros1 Dimension:  1
Zeros1 Shape:  torch.Size([3])
Zeros1 data type:  torch.float32
----------------------------------
Ones1: 
tensor([1., 1., 1.])
Ones1 Dimension:  1
Ones1 Shape:  torch.Size([3])
Ones1 data type:  torch.float32


### 2. Matrix

In [10]:
zeros2 = torch.zeros(3,2)
print("Zeros2: ")
print(zeros2)
print("Zeros2 Dimension: ", zeros2.ndim)
print("Zeros2 Shape: ", zeros2.shape)
print("Zeros2 data type: ", zeros2.dtype)
print("----------------------------------")
ones2 = torch.ones(3,2)
print("Ones2: ")
print(ones2)
print("Ones2 Dimension: ", ones2.ndim)
print("Ones2 Shape: ", ones2.shape)
print("Ones2 data type: ", ones2.dtype)

Zeros2: 
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
Zeros2 Dimension:  2
Zeros2 Shape:  torch.Size([3, 2])
Zeros2 data type:  torch.float32
----------------------------------
Ones2: 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
Ones2 Dimension:  2
Ones2 Shape:  torch.Size([3, 2])
Ones2 data type:  torch.float32


### 3. Tensor

In [11]:
zeros3 = torch.zeros(2, 3,2)
print("Zeros3: ")
print(zeros3)
print("Zeros3 Dimension: ", zeros3.ndim)
print("Zeros3 Shape: ", zeros3.shape)
print("Zeros3 data type: ", zeros3.dtype)
print("----------------------------------")
ones3 = torch.ones(2,3,2)
print("Ones3: ")
print(ones3)
print("Ones3 Dimension: ", ones3.ndim)
print("Ones3 Shape: ", ones3.shape)
print("Ones3 data type: ", ones3.dtype)

Zeros3: 
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])
Zeros3 Dimension:  3
Zeros3 Shape:  torch.Size([2, 3, 2])
Zeros3 data type:  torch.float32
----------------------------------
Ones3: 
tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
Ones3 Dimension:  3
Ones3 Shape:  torch.Size([2, 3, 2])
Ones3 data type:  torch.float32


> ## Ranging Tensors

Rangind tensor library enables user to set start and end number with specific step to generate the tensor. 

In [12]:
range = torch.arange(start=-0, end=10, step=1)
print("Range:")
print(range)
print("Range Dimension: ", range.ndim)
print("Range Shape: ", range.shape)

Range:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Range Dimension:  1
Range Shape:  torch.Size([10])


> ## Manipulating Tensor (Arithmetic Operation)

In DL, changing values of weights and bias are key operation of training the neural network model. In order to change the values, performing series of arithmetic operation is required such as

* Addion
* Subtraction
* Multiplication (Element-wise)
* Division
* Matrix Multiplication or dot product

If you are not sure about each of the step, I will show specific steps of each calculation.



### 1. Basic Operation: Broadcast

You all know addition, subtraction, multiplication, and division from your elementry school. Performing basic arithmetic operation in tensor are exactly the same. 

In [13]:
tensor = torch.tensor([10,20,30])
print("Tensor: \n", tensor)
# Addition
addition = tensor + 10
print("\nAddition: \n", addition)

# Subtraction
subtraction = tensor - 10
print("\nSubtraction: \n", subtraction)

# Multiplication
multiplication = tensor * 10
print("\nMultiplication: \n", multiplication)

# Division
division = tensor / 10
print("\nDivision: \n", division)

Tensor: 
 tensor([10, 20, 30])

Addition: 
 tensor([20, 30, 40])

Subtraction: 
 tensor([ 0, 10, 20])

Multiplication: 
 tensor([100, 200, 300])

Division: 
 tensor([1., 2., 3.])


### 2. Basic Operation: Element-Wise

After performing arithemetic operation by broadcasting a single value onto the vector, arithemetic operation can be performed in "Element-Wise."

In [14]:
#Tensors
tensor = torch.tensor([[1,2,3],
                       [4,5,6]])

tensor2 = torch.tensor([[2,3,4],
                        [5,6,7]])
print("Tensor: \n", tensor)
print("\nTensor2: \n", tensor2)

# Addition
addition = tensor + tensor2
print("\nAddition: \n", addition)

# Subtraction
subtraction = tensor - tensor2
print("\nSubtraction: \n", subtraction)

# Multiplication
multiplication = tensor * tensor2
print("\nMultiplication: \n", multiplication)

# Division
division = tensor / tensor2
print("\nDivision: \n", division)

Tensor: 
 tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor2: 
 tensor([[2, 3, 4],
        [5, 6, 7]])

Addition: 
 tensor([[ 3,  5,  7],
        [ 9, 11, 13]])

Subtraction: 
 tensor([[-1, -1, -1],
        [-1, -1, -1]])

Multiplication: 
 tensor([[ 2,  6, 12],
        [20, 30, 42]])

Division: 
 tensor([[0.5000, 0.6667, 0.7500],
        [0.8000, 0.8333, 0.8571]])


### 3. Multiplication (Dot-Product)

Matrix multiplication or dot product is multiplying each row of the first matrix onto each column of the second matrix. Calculation method for vector and matrix is a bit different. 

Assume we have vector = [1,2,3]

| Operation | Calculation | Code |
| ----- | ----- | ----- |
| **Element-wise multiplication** | `[1*1, 2*2, 3*3]` = `[1, 4, 9]` | `tensor * tensor` |
| **Vector multiplication** | `[1*1 + 2*2 + 3*3]` = `[14]` | `tensor.matmul(tensor)` |

#### 1. Vector Muliplication


In [15]:
vector = torch.tensor([1,2,3])
torch.matmul(vector, vector)

tensor(14)

#### 2. Matrix Muliplication

1. The **inner dimensions** must match:
  * `(3, 2) @ (3, 2)` won't work
  * `(2, 3) @ (3, 2)` will work
  * `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the **outer dimensions**:
 * `(2, 3) @ (3, 2)` -> `(2, 2)`
 * `(3, 2) @ (2, 3)` -> `(3, 3)`

In [16]:
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])
matrix2 = torch.tensor([[1,4],
                        [2,5],
                        [3,6]])
torch.matmul(matrix, matrix2)

tensor([[14, 32],
        [32, 77]])

3. Common mistak on matrix multiplication and solution

In [17]:
# Shapes need to be in the right way  
matrix = torch.tensor([[1,2,3],
                       [4,5,6]])
matrix2 = torch.tensor([[1,2,3],
                        [4,5,6]])

#torch.matmul(tensor_A, tensor_B) # (this will error)

In [20]:
tensor_result = torch.mm(matrix, matrix2.T)
print("Matrix: \n", matrix)
print("\nMatrix2: \n", matrix2)
print("\nMatrix2 Transpose: \n", matrix2.T)
print("\nMatrix Multiplication: \n", tensor_result)

Matrix: 
 tensor([[1, 2, 3],
        [4, 5, 6]])

Matrix2: 
 tensor([[1, 2, 3],
        [4, 5, 6]])

Matrix2 Transpose: 
 tensor([[1, 4],
        [2, 5],
        [3, 6]])

Matrix Multiplication: 
 tensor([[14, 32],
        [32, 77]])


> ## Tensor Analysis

Like numpy and pandas, PyTorch tensor also provide useful tool for analyze numbers of the tensor. 

### Max, Min, Mean, Sum...

In [37]:
tensor = torch.arange(10.0,110.0,10.0)
print("Tensor: \n", tensor)
print("\nMax: \n", torch.max(tensor, 0))
print("\nMin: \n", torch.min(tensor, 0))
print("\nMean: \n", tensor.mean())
print("\nSum: \n", tensor.sum())

Tensor: 
 tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Max: 
 torch.return_types.max(
values=tensor(100.),
indices=tensor(9))

Min: 
 torch.return_types.min(
values=tensor(10.),
indices=tensor(0))

Mean: 
 tensor(55.)

Sum: 
 tensor(550.)


In [35]:
tensor = torch.rand(3,2)
print("Tensor: \n", tensor)
print("\nAxis 0 Max: \n", torch.max(tensor, 0))
print("\nAxis 1 Max: \n", torch.max(tensor, 1))

Tensor: 
 tensor([[0.4391, 0.1579],
        [0.2629, 0.1590],
        [0.8009, 0.8872]])

Axis 0 Max: 
 torch.return_types.max(
values=tensor([0.8009, 0.8872]),
indices=tensor([2, 2]))

Axis 1 Max: 
 torch.return_types.max(
values=tensor([0.4391, 0.2629, 0.8872]),
indices=tensor([0, 0, 1]))


In [39]:
tensor = torch.rand(2, 3,2)
print("Tensor: \n", tensor)
print("\nAxis 0 Max: \n", torch.max(tensor, 0))
print("\nAxis 1 Max: \n", torch.max(tensor, 1))
print("\nAxis 2 Max: \n", torch.max(tensor, 2))

Tensor: 
 tensor([[[0.1691, 0.0228],
         [0.1954, 0.2037],
         [0.2305, 0.8955]],

        [[0.3570, 0.3020],
         [0.0480, 0.4371],
         [0.7935, 0.0069]]])

Axis 0 Max: 
 torch.return_types.max(
values=tensor([[0.3570, 0.3020],
        [0.1954, 0.4371],
        [0.7935, 0.8955]]),
indices=tensor([[1, 1],
        [0, 1],
        [1, 0]]))

Axis 1 Max: 
 torch.return_types.max(
values=tensor([[0.2305, 0.8955],
        [0.7935, 0.4371]]),
indices=tensor([[2, 2],
        [2, 1]]))

Axis 2 Max: 
 torch.return_types.max(
values=tensor([[0.1691, 0.2037, 0.8955],
        [0.3570, 0.4371, 0.7935]]),
indices=tensor([[0, 1, 1],
        [0, 1, 0]]))


> ## Change Data Type

When operating arithematic computation between or among different tensors, not only matching the inner size of the tensors is important but also matching the type of the tensor is essential. 

In [44]:
tensor = torch.rand(10)
print("Tensor: \n", tensor)
print("\nTensor data type: \n", tensor.dtype)

Tensor: 
 tensor([0.0864, 0.0423, 0.8625, 0.2813, 0.9311, 0.5569, 0.9499, 0.4768, 0.3788,
        0.7359])

Tensor data type: 
 torch.float32


In [45]:
tensor_to_float16 = tensor.type(torch.float16)
print("Tensor: \n", tensor_to_float16)
print("\nTensor data type: \n", tensor_to_float16.dtype)

Tensor: 
 tensor([0.0864, 0.0423, 0.8623, 0.2812, 0.9312, 0.5571, 0.9497, 0.4768, 0.3789,
        0.7358], dtype=torch.float16)

Tensor data type: 
 torch.float16


In [46]:
tensor_to_int8 = tensor.type(torch.int8)
print("Tensor: \n", tensor_to_int8)
print("\nTensor data type: \n", tensor_to_int8.dtype)

Tensor: 
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int8)

Tensor data type: 
 torch.int8
